### ISSUE TITLE
Support for Cyclist

### ISSUE THREAD

**Issue by JHenneberg** [bokub/stravanity#2]
Great Projects. Being a cyclist I am looking for the same except for cyclist segments. Would be this smth complicated to implement?

**Comment by bokub** [comment]
Hi,

I don't think it's very complicated, actually it's only one line of code to change:

https://github.com/bokub/stravanity/blob/b8f7c38792de3e04879ecc8a5d450899c65a5913/src/App.vue#L95

Maybe I'll add a toggle someday, but I'm quite busy at the moment.

**Comment by JHenneberg** [comment]
Thanks for the feedback. 
Would you accept a PR providing this?

**Comment by bokub** [comment]
Sure ! That would be great

**Comment by JHenneberg** [comment]
Its all for my own benefit. I need this feature :P.
I will give it a try, but I have to admit I have never done a web app of any kind, so I definitley need a code review.

**Comment by JHenneberg** [comment]
Any Idea? I am stuck
I tried different ways to configure on `https://www.strava.com/settings/api`

added
```typescript
params.append('approval_prompt', 'force');
```
to the request.
Added some logging but I can not find any mistake.

**Comment by JHenneberg** [comment]
Thanks a lot that seems to work. 
With the `VUE_APP_HERE_MAPS_API_KEY` were no problems after registrating one of my own and making it availuable for the app.

**Comment by swoopinghawk** [comment]
I've no clue about programming, but just chiming in that I also would love this feature. Did you perhaps make a working website as well JHenneberg? Thanks either way, both of you!

**Comment by JHenneberg** [comment]
I stopped further investigating for several reasons. Mainly because I am not a web developer at all and the overhead implementing the easiest things is quite big for me. 
But even building a CLI tool how the easiest segment could be found is not as trivial as it might look on the first glance.

1. First you need to come up with an equation which gives you some sort of a rating for a segment (thats the hardest part). I thought most easy it would be to get a lot of segments data and do a curve fitting. But how to get this data? The strava API is not allowing to many requests and you need a lot of data.
3. Then you need to correlate speed and rating to be able to judge if a segment was driven fast for the rating or not.
4. Lastly you can search for actual beatable segments.

There some basic assumptions like so:
  * the steeper the segment, the harder it gets
  * the longer the segment, the harder it gets

**Comment by cbibbs** [comment]
What IDE did you use? I wanted to run it in Webstorm, but there isn't a configuration in the project.

**Comment by bokub** [comment]
Why would you need a configuration?

**Comment by cbibbs** [comment]
> vue-cli-service serve
> 
> sh: vue-cli-service: command not found

I assume there's something missing in my configuration.

**Comment by cbibbs** [comment]
I found my issues. The version of node-sass you specified in the project isn't compatible with the latest node for MacOS. I force downgraded and it's running fine.

**Comment by bokub** [comment]
The support for cyclists is now available thanks to @sourcx ! :tada:
