### ISSUE TITLE
What's in the ifttt trigger

### ISSUE THREAD

**Issue by sourcx** [bokub/stravanity#4]
Hi @bokub,

I'm reading your code trying to understand what everything is doing and am wondering what you're doing in your endpoint `https://maker.ifttt.com/trigger/stravanity` with the `payload.athlete` data?

Cheers,
sourcx

**Comment by bokub** [comment]
Hi @sourcx !
This endpoint sends the athlete data to IFTTT, which saves the athlete ID in a Google sheets spreadsheet.

The goal of this is only to count how many unique users use my app, which is helpful to decide how much time I want to dedicate to improve stravanity

In a nutshell: just analytics for myself

Hope it helps!

**Comment by sourcx** [comment]
Alright thanks for your reply! 

FYI I'm currently running your app myself to see if I can adapt it for cycling (I read more people are interested in this) and to learn about the software stack you chose.

I am also wondering if you copy the `access_token` from prod to localhost when you're developing?

**Comment by bokub** [comment]
Good to know!

I was planning to add a toggle button to switch between running and cycling, but if you can do it yourself, that's great! (it's in my TODO list, I just have more urgent projects at the moment)

Feel free to open a PR and ask other questions. And yes, copying the production cookie to localhost should work!
